Apple's gcc choked on the assembly in i386.c:   i386.c: In function `_control87':   i386.c:31: error: PIC register `bx' clobbered in `asm'
This is because -fPIC is enabled on Mac OS X by default.
To avoid this, I changed all references to bx to cx.

I have confirmed that the code compiles and functions correctly
after this change.